image: php:7.1.3

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng12-dev libzip-dev zip
          - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
          - docker-php-ext-install gd
          - docker-php-ext-configure zip --with-libzip
          - docker-php-ext-install zip
          - apt-get install -qy git curl libmcrypt-dev mysql-client
          - docker-php-ext-install pdo_mysql
          - ./composer.phar install --no-interaction --prefer-dist --optimize-autoloader
          - cp .env.testing .env
          - php artisan migrate --force
          - php artisan cache:clear
          - ./vendor/bin/phpunit
        services:
          - mysql
definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'pipelines'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'test_user'
        MYSQL_PASSWORD: 'root@test_user_password'
